### ISSUE TITLE
make it mobile usable

### ISSUE THREAD

**Issue by itaditya** [itaditya/trick-or-treat-game#13]
## Requires

* Gestures or virtual keys to control movement.
* Responsive design

**Comment by gabLaroche** [comment]
I'd like to work on this. :)

**Comment by itaditya** [comment]
Great @gabLaroche. If you find any issue in setting up the project let me know. I'd suggest first thinking what way would be best for user to Control the Game.

Suggestions-
1. Virtual up/down right/left keys on bottom of board.
2. Instead of portrait mode, we can ask user to play game in landscape mode, then up/right virtual buttons can be on the left side of board and left/right buttons can be on the right side.
3. Use gestures. (Although I think this would not be the best way since there is so many times user have to swipe. With above solutions user would only need to tap).

**Comment by itaditya** [comment]
@gabLaroche fixed #13 so closing the Issue
