### ISSUE TITLE
make a logo for the game.

### ISSUE THREAD

**Issue by itaditya** [itaditya/trick-or-treat-game#15]
The game is missing a logo. The logo is needed for various places.

1. Game Logo at top left (180x180).
2. Favicon (24x24).
3. PWA icon (48x48, 128x128).

**Comment by abhayjatindoshi** [comment]
I can design a logo. Can you help me with the sizes and places where the logo's will be used.

**Comment by itaditya** [comment]
I have updated the issue description.

**Comment by abhayjatindoshi** [comment]
How about this icon ?
![image](https://user-images.githubusercontent.com/19318032/66022348-58e03380-e50b-11e9-9401-8fb1d359d716.png)

**Comment by itaditya** [comment]
Looks good to me

**Comment by abhayjatindoshi** [comment]
Ohh !! the background. Don't worry about it. It is a snap from PS. It will be transparent. Also in any web developer's favourite format. SVG. so we would be able to scale up and down easily.

**Comment by itaditya** [comment]
I still think we should have a colored background. At the very least, the eyes and mouth should have a fill color because otherwise they might not look good everywhere.

**Comment by abhayjatindoshi** [comment]
#41

**Comment by itaditya** [comment]
closed by #41
