### ISSUE TITLE
Add a Scoreboard which stores data in localStorage

### ISSUE THREAD

**Issue by itaditya** [itaditya/trick-or-treat-game#16]
Currently whatever the score user achieves gets lost once they refresh. It would be great if on the left side of the game board we show a scoreboard of scores from least moves at the top to most moves at the bottom.

All the data can be stored in localStorage.

**Comment by sohammondal** [comment]
I want to work on this.

**Comment by itaditya** [comment]
@sohammondal thanks for volunteering to work on this. These are great questions.

1. Feature branch- `soham-add-scoreboard`.
2. I'll draw a mockup of the layout with scoreboard. For the design a list (with numbers) with heading would do (in white color with visual hierarchy).

Something like

### Scoreboard

1. someuser1 - 45
2. someuser2 - 40
3. someuser1 - 30
4. someuser1 - 15
 
Things to note-

1. List goes from highest score to lowest score.
2. Once user finishes a game, beside the score, we'll show an input box where they can enter a username. Then in localstorage the score will be saved along with username.

**Comment by sohammondal** [comment]
@itaditya Thanks for the answers. However, I raised a PR #23  just a few mins ago, please ignore that. I will make the necessary changes.

**Comment by itaditya** [comment]
Oops I made a mistake. the order you currently have is totally right. Least moves === Highest score. I'll update the comment

**Comment by sohammondal** [comment]
Got it. No issue. All features implemented. Please check the PR #24

**Comment by itaditya** [comment]
Issue fixed by #24
