### ISSUE TITLE
Play background audio on page load

### ISSUE THREAD

**Issue by itaditya** [itaditya/trick-or-treat-game#17]
Steps-

1. Pick a Halloween theme tune.
2. Lazy load an audio track.
3. Play that audio in background.
4. Make sure no control of audio is visible to user.

If the user needs to stop audio they can just mute it from the tab. We don't need to do anything ourselves.

**Comment by kemda26** [comment]
i'll do it

**Comment by itaditya** [comment]
fixed by @kemda26 in #21.
