### ISSUE TITLE
Add a section to explain instructions to play the game.

### ISSUE THREAD

**Issue by itaditya** [itaditya/trick-or-treat-game#42]
The game can be played by keyboard on desktop and virtual keys on phone. The play on phone is self explanatory but on desktop, user won't know which key to press. Having a paragraph on the page to tell that `->` key moves the player to left and so on would be very helpful.

Also it might not be obvious that user has to get all candies in minimum moves so some cool to show that is also needed.

**Comment by rajat2502** [comment]
I can work on this issue.

**Comment by itaditya** [comment]
Cool, assigning it to you.

**Comment by manAbl** [comment]
Hey, :(  forgot to mention I'm working on this issue already

**Comment by itaditya** [comment]
@manAbl really sorry friend. If you informed me beforehand I would have assigned you on this task. Since Rajat got it assigned, I reviewed his code and it has now been merged.

There are many other open issues right now. Let me know if you want to work on any of those. I'll be glad to help you out!
