### ISSUE TITLE
Increase mobile width breakpoint to 600px

### ISSUE THREAD

**Issue by rajat2502** [itaditya/trick-or-treat-game#47]
The Mobile view width is 480px right now which is less than the width of most of the standard mobile phones so changing it to 600px will make it responsive to a wide range of mobile phones.

**Comment by itaditya** [comment]
480 px is used as width breakpoint not a height breakpoint.

**Comment by rajat2502** [comment]
fixed that

**Comment by itaditya** [comment]
@rajat2502 can you make a PR for this. Make sure to update all the places where breakpoint 480px is used.

**Comment by rajat2502** [comment]
Ok, I will work on it.
