### ISSUE TITLE
Add GitHub ribbon with link to this project.

### ISSUE THREAD

**Issue by itaditya** [itaditya/trick-or-treat-game#73]
Make a React component with name `GitHubRibbon`. Inside it render this GitHub ribbon.

Then use the GitHubRibbon component inside `index.js` file

Pick the 5th one from the top.
<img width="776" alt="image" src="https://user-images.githubusercontent.com/15871340/66498462-b95b0c00-eadb-11e9-9d30-b46b4a7d4150.png">

**Issue will only be assigned to people I'm mentoring under Road to Hacktober programme. Other people please find other repos of mine to contribute for Hacktoberfest.**

**Comment by shivanshBTW** [comment]
I want to work on this issue

**Comment by shivanshBTW** [comment]
added in #74
